### ISSUE TITLE
contact us email capitalizing

### ISSUE THREAD

**Issue by AlwaysLearning55** [AlwaysLearning55/MA-7.github.io#1]
Capitalize the email on the MA-7 page.
![image](https://user-images.githubusercontent.com/16280366/106346033-d3050180-6292-11eb-863a-89294c10d8f9.png)

**Comment by 96RadhikaJadhav** [comment]
@AlwaysLearning55  Can I work on the issue?

**Comment by AlwaysLearning55** [comment]
Assigned to @96RadhikaJadhav

**Comment by rocklikereeju00** [comment]
Can I work on this issue

**Comment by AlwaysLearning55** [comment]
Issue solved by @96RadhikaJadhav .
Excelent job!
